name: Dev

on:
  #push:
  #  branches:
  #    - dev
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Enable Corepack
        run: corepack enable
        
      - name: Install npm packages and build storybook
        run: yarn install
        
      - name: Build app
        run: yarn build

      # Publish to azure static web apps
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Action to perform
          action: 'upload'
          # Directory location of the application source code
          app_location: ./public/
          # Required token
          azure_static_web_apps_api_token: ${{ secrets.DEV_AZURE_SWA_TOKEN }}
          # Skips the build step for the application source code if set to true.
          skip_app_build: true
