name: Master

on:
  #push:
  #  branches:
  #    - master
  workflow_dispatch:

env:
  GATSBY_AZURE_TABLES_ACCOUNT: ${{ secrets.PROD_AZURE_TABLES_ACCOUNT }}
  GATSBY_AZURE_TABLES_SAS: ${{ secrets.PROD_AZURE_TABLES_SAS }}

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.PROD_AZURE_SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" 
          output_location: "public"
